# Generated by Django 5.1.5 on 2025-02-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Targets',
        ),
    ]
