# Generated by Django 5.1.5 on 2025-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_delete_production_delete_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('420', '420'), ('428', '428'), ('CAM', 'CAM')], max_length=50)),
                ('part', models.CharField(choices=[('Inner Plate', 'Inner Plate'), ('Outer Plate', 'Outer Plate'), ('Pin', 'Pin'), ('Bush', 'Bush'), ('Roller', 'Roller')], max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
